# Generated by Django 4.2.27 on 2025-12-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_post_slug_post_views_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name'], 'verbose_name': '태그', 'verbose_name_plural': '태그 목록'},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(default=1, help_text='이 태그가 속한 카테고리', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.category', verbose_name='카테고리'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='태그명'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(verbose_name='슬러그'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('category', 'name')},
        ),
    ]
