# Generated by Django 4.2.27 on 2025-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tag_options_tag_category_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='예약발행 시 공개될 날짜와 시간', null=True, verbose_name='발행 예정일'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('published', '발행됨'), ('scheduled', '예약발행')], default='draft', max_length=10, verbose_name='상태'),
        ),
    ]
