# Generated by Django 4.2.27 on 2025-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published_at_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='검색 결과에 표시될 설명 (160자 이내)', max_length=160, verbose_name='메타 설명'),
        ),
    ]
