# Generated by Django 4.2.27 on 2025-12-26 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='숨김'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '스팸/광고'), ('abuse', '욕설/비방'), ('hate', '혐오/차별'), ('illegal', '불법 정보'), ('other', '기타')], max_length=10, verbose_name='신고 사유')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.comment', verbose_name='댓글')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '댓글 신고',
                'verbose_name_plural': '댓글 신고 목록',
                'ordering': ['-created_at'],
                'unique_together': {('comment', 'reporter')},
            },
        ),
    ]
