# Generated by Django 4.2.27 on 2025-12-27 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='자기소개')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='프로필 이미지')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub')),
                ('skills', models.TextField(blank=True, help_text='쉼표로 구분하여 입력 (예: Python, Django, JavaScript)', verbose_name='기술 스택')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
            },
        ),
    ]
